name: "dbt_postgres_project"

version: "1.0"
config-version: 2

profile: "dbt_postgres_project"

model-paths: ["models"]
seed-paths:  ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
test-paths:    ["tests"]
analysis-paths: ["analyses"]

quoting:
  database: false
  schema: false
  identifier: false

models:
  +on_schema_change: append_new_columns   # friendly during iteration

  dbt_postgres_project:
    silver:
      +schema: silver
      +materialized: table                  # silver tables are persisted